import { NextRequest, NextResponse } from "next/server";
import { ApiResponse } from "@/lib/types";

// Helper function to extract JSON from AI response text
function extractJson(text: string): any {
  // Try to find code block patterns first
  const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  const cleanText = jsonMatch ? jsonMatch[1].trim() : text.trim();
  
  try {
    return JSON.parse(cleanText);
  } catch (e) {
    // If that fails, try to search for the first '{' and last '}'
    const firstBrace = text.indexOf('{');
    const lastBrace = text.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      const parsedText = text.substring(firstBrace, lastBrace + 1);
      return JSON.parse(parsedText);
    }
    throw e;
  }
}

// Helper function to dynamically compile a premium HTML template using copy generated by AI
function buildHtmlPage(analysis: any, bonuses: any[], bonusPage: any): string {
  const productName = analysis.productName || "Exclusive Product";
  const headline = bonusPage.headline || `Get Exclusive Bonuses For ${productName}`;
  const subheadline = bonusPage.subheadline || "Get instant access to my custom-curated, high-value bonuses when you grab this product through this page.";
  const ctaText = bonusPage.ctaText || "Claim Your Bonuses & Get Started Now";
  const bonusStackDescription = bonusPage.bonusStackDescription || "To help you succeed faster and get the absolute most out of this product, I have put together a massive custom bonus package. These bonuses are 100% exclusive and designed to resolve limitations and maximize your results.";
  const scarcitySection = bonusPage.scarcitySection || "Warning: This special bonus package is highly limited. It is only available to the first 50 action takers. Once the slots are full, this offer will expire forever.";
  const closingSection = bonusPage.closingSection || "Remember, there is zero risk. You are fully protected by the product's official refund guarantee, and all my custom bonuses are yours to keep. Click the button below to secure your copy and bonuses now.";

  const items = Array.isArray(bonuses) ? bonuses : [];
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${headline}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body {
      background-color: #030014;
      color: #f1f5f9;
      font-family: ui-sans-serif, system-ui, sans-serif;
    }
    .grid-bg {
      background-size: 40px 40px;
      background-image: 
        linear-gradient(to right, rgba(255, 255, 255, 0.015) 1px, transparent 1px),
        linear-gradient(to bottom, rgba(255, 255, 255, 0.015) 1px, transparent 1px);
    }
    .glow-radial {
      background: radial-gradient(circle, rgba(124, 58, 237, 0.1) 0%, transparent 60%);
    }
    .glass-card {
      background: rgba(15, 12, 30, 0.5);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border: 1px solid rgba(255, 255, 255, 0.06);
    }
  </style>
</head>
<body class="grid-bg min-h-screen py-16 px-4 md:px-8 relative selection:bg-violet-500/30">
  <!-- Decorative Glow -->
  <div class="absolute top-0 left-1/4 w-[500px] h-[500px] glow-radial pointer-events-none rounded-full" />
  <div class="absolute bottom-0 right-1/4 w-[500px] h-[500px] glow-radial pointer-events-none rounded-full" />

  <div class="max-w-5xl mx-auto flex flex-col gap-12 relative z-10">
    <!-- Header -->
    <header class="text-center flex flex-col gap-5">
      <span class="text-xs font-bold uppercase tracking-widest text-violet-400 bg-violet-500/10 border border-violet-500/20 px-3.5 py-1.5 rounded-full self-center">
        Exclusive Special Offer
      </span>
      <h1 class="text-4xl md:text-6xl font-black tracking-tight text-white leading-tight max-w-4xl mx-auto animate-fadeIn">
        ${headline}
      </h1>
      <p class="text-slate-400 text-lg md:text-xl max-w-3xl mx-auto font-medium">
        ${subheadline}
      </p>
    </header>

    <!-- Scarcity Box -->
    <div class="bg-amber-950/20 border border-amber-500/20 rounded-2xl p-6 text-center shadow-lg shadow-amber-500/5 max-w-3xl mx-auto w-full">
      <div class="flex items-center justify-center gap-2 mb-1">
        <span class="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
        <p class="text-amber-400 font-bold text-xs uppercase tracking-wider">Limited Bonus Slots Remaining</p>
      </div>
      <p class="text-white text-base font-semibold">${scarcitySection}</p>
    </div>

    <!-- Intro Text -->
    <div class="glass-card rounded-2xl p-6 md:p-8 max-w-4xl mx-auto w-full">
      <h3 class="text-xl font-bold text-white mb-2">The Value Stack Details</h3>
      <p class="text-slate-300 leading-relaxed text-sm md:text-base">${bonusStackDescription}</p>
    </div>

    <!-- Bonuses Grid -->
    <div class="flex flex-col gap-6 w-full max-w-4xl mx-auto animate-fadeIn">
      <h2 class="text-2xl font-bold text-white border-b border-white/5 pb-3 flex items-center gap-2">
        <span>Exclusive Custom Bonuses (Worth Thousands)</span>
      </h2>
      
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        ${items.map((bonus, idx) => `
          <div class="glass-card rounded-2xl p-6 flex flex-col gap-4 relative overflow-hidden">
            <span class="absolute top-0 right-0 bg-violet-600/10 border-l border-b border-white/5 text-violet-400 text-xs font-bold px-3 py-1.5 rounded-bl-xl">
              Bonus #${idx + 1}
            </span>
            <div class="flex flex-col gap-2">
              <div class="flex flex-wrap gap-1.5 items-center">
                <span class="text-[10px] font-semibold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                  Value: ${bonus.estimatedValue || '$97'}
                </span>
                <span class="text-[10px] font-semibold text-violet-400 bg-violet-500/10 px-2 py-0.5 rounded border border-violet-500/20">
                  Format: ${bonus.deliveryFormat || 'Swipe File'}
                </span>
              </div>
              <h4 class="text-lg font-bold text-white pr-16">${bonus.name}</h4>
            </div>
            <p class="text-slate-300 text-sm leading-relaxed">${bonus.description}</p>
            <div class="mt-auto bg-white/5 p-3.5 rounded-xl border border-white/5 flex flex-col gap-2.5">
              <div>
                <span class="text-[10px] text-violet-400 font-bold block uppercase tracking-wider mb-0.5">How it helps you succeed:</span>
                <p class="text-slate-300 text-xs leading-relaxed">${bonus.whyItHelps}</p>
              </div>
              <div class="border-t border-white/5 pt-2 flex flex-col gap-1">
                <div>
                  <span class="text-[10px] text-cyan-400 font-bold block uppercase tracking-wider">Objection Solved:</span>
                  <p class="text-slate-300 text-xs italic leading-relaxed">${bonus.objectionSolved}</p>
                </div>
                <div class="border-t border-white/5 pt-1.5">
                  <span class="text-[10px] text-emerald-400 font-bold block uppercase tracking-wider">Conversion Benefit:</span>
                  <p class="text-slate-300 text-xs italic leading-relaxed">${bonus.conversionBenefit}</p>
                </div>
              </div>
            </div>
          </div>
        `).join('')}
      </div>
    </div>

    <!-- CTA Section -->
    <div class="text-center py-8 flex flex-col items-center gap-4 max-w-xl mx-auto">
      <a href="#" class="inline-flex items-center justify-center px-8 py-4 bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white font-bold text-lg rounded-xl shadow-lg shadow-violet-500/20 transition-all hover:scale-105 active:scale-95">
        ${ctaText}
      </a>
      <p class="text-xs text-slate-500">Note: Use my affiliate link during checkout to ensure you receive all bonuses. All assets will be delivered instantly after checkout.</p>
    </div>

    <!-- Closing Section -->
    <div class="border-t border-white/5 pt-8 text-center text-sm text-slate-400 max-w-xl mx-auto leading-relaxed">
      <p>${closingSection}</p>
    </div>
  </div>
</body>
</html>`;
}

// Custom runtime validation for safety
function isValidApiResponse(json: any): json is ApiResponse {
  if (!json || typeof json !== 'object') return false;
  
  const { analysis, bonuses, bonusPage, emails } = json;
  
  if (!analysis || typeof analysis !== 'object') return false;
  if (typeof analysis.productName !== 'string') return false;
  if (typeof analysis.targetAudience !== 'string') return false;
  if (!Array.isArray(analysis.features)) return false;
  if (!Array.isArray(analysis.benefits)) return false;
  if (!Array.isArray(analysis.painPoints)) return false;
  if (typeof analysis.usp !== 'string') return false;
  if (!Array.isArray(analysis.marketingAngles)) return false;
  
  if (!Array.isArray(bonuses)) return false;
  // Ensure we have at least some bonuses (target 10, but let's be flexible to not fail if we get 8-10, though prompt asks for 10)
  if (bonuses.length === 0) return false;
  for (const b of bonuses) {
    if (typeof b.name !== 'string' || typeof b.description !== 'string' || typeof b.whyItHelps !== 'string' || typeof b.estimatedValue !== 'string') {
      return false;
    }
    if (typeof b.deliveryFormat !== 'string' || typeof b.conversionBenefit !== 'string' || typeof b.objectionSolved !== 'string') {
      return false;
    }
  }
  
  if (!bonusPage || typeof bonusPage !== 'object') return false;
  if (typeof bonusPage.headline !== 'string') return false;
  if (typeof bonusPage.subheadline !== 'string') return false;
  if (typeof bonusPage.ctaText !== 'string') return false;
  if (typeof bonusPage.bonusStackDescription !== 'string') return false;
  if (typeof bonusPage.scarcitySection !== 'string') return false;
  if (typeof bonusPage.closingSection !== 'string') return false;
  if (typeof bonusPage.htmlTemplate !== 'string') return false;
  
  if (!Array.isArray(emails)) return false;
  if (emails.length === 0) return false;
  for (const e of emails) {
    if (typeof e.type !== 'string' || typeof e.subject !== 'string' || typeof e.previewText !== 'string' || typeof e.body !== 'string' || typeof e.ctaText !== 'string') {
      return false;
    }
  }
  
  return true;
}

export async function POST(req: NextRequest) {
  try {
    const { url, fallbackContent, openRouterKey, selectedModel } = await req.json();

    let contentToAnalyze = "";

    // 1. Scrape with Jina Reader if URL is provided
    if (url && url.trim() !== "") {
      let targetUrl = url.trim();
      if (!/^https?:\/\//i.test(targetUrl)) {
        targetUrl = "https://" + targetUrl;
      }
      
      try {
        const jinaUrl = `https://r.jina.ai/${targetUrl}`;
        const response = await fetch(jinaUrl, {
          method: "GET",
          headers: {
            "Accept": "text/plain",
            "X-Return-Format": "markdown"
          },
          signal: AbortSignal.timeout(12000) // 12-second timeout for Jina
        });

        if (response.ok) {
          contentToAnalyze = await response.text();
        } else {
          console.warn(`Jina Reader failed with status: ${response.status}`);
        }
      } catch (scrapeErr) {
        console.error("Error scraping with Jina Reader:", scrapeErr);
      }
    }

    // 2. Fallback to manual content if scraping failed or was not requested
    if (!contentToAnalyze || contentToAnalyze.trim().length < 50) {
      if (fallbackContent && fallbackContent.trim().length >= 10) {
        contentToAnalyze = fallbackContent.trim();
      } else {
        return NextResponse.json(
          {
            error: "Scraping failed, and no fallback sales page content was pasted. Please enter sales page content manually.",
            scrapingFailed: true
          },
          { status: 400 }
        );
      }
    }

    // Truncate input text to avoid token overflow (around 15000 chars is fine for Gemini/DeepSeek)
    if (contentToAnalyze.length > 25000) {
      contentToAnalyze = contentToAnalyze.substring(0, 25000) + "... [Truncated]";
    }

    // 3. Setup OpenRouter call
    const apiKey = (openRouterKey && openRouterKey.trim() !== "") ? openRouterKey.trim() : process.env.OPENROUTER_API_KEY;
    const model = (selectedModel && selectedModel.trim() !== "") ? selectedModel.trim() : (process.env.OPENROUTER_MODEL || "google/gemini-2.5-flash");

    if (!apiKey) {
      return NextResponse.json(
        {
          error: "API Key Missing: Please provide your OpenRouter API Key in the settings panel, or configure OPENROUTER_API_KEY on the server."
        },
        { status: 400 }
      );
    }

    const systemPrompt = `You are a world-class affiliate marketer, copywriting expert, and SaaS product architect.
Analyze the provided sales page content and output a comprehensive affiliate promotion suite.

You MUST return your response as a single, valid JSON object matching the exact schema below. Do not output any introductory or explanatory text. Do not wrap the JSON in any markdown other than optionally a json code block.

JSON Schema:
{
  "analysis": {
    "productName": "Name of the product",
    "targetAudience": "Clear description of the ideal buyer",
    "features": ["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"],
    "benefits": ["Benefit 1", "Benefit 2", "Benefit 3", "Benefit 4", "Benefit 5"],
    "painPoints": ["Pain point 1 resolved", "Pain point 2 resolved", "Pain point 3 resolved"],
    "usp": "Unique Selling Proposition",
    "marketingAngles": ["Angle 1", "Angle 2", "Angle 3"]
  },
  "bonuses": [
    {
      "name": "Bonus 1 Name",
      "description": "Detailed description of what the buyer receives",
      "whyItHelps": "Explains how this bonus directly plugs a gap in the main product, resolves an objection, or helps the buyer implement it twice as fast",
      "estimatedValue": "$97",
      "deliveryFormat": "Must be one of: PDF, Video Course, Templates, Swipe File, Prompt Pack, Toolkit",
      "conversionBenefit": "A clear, compelling explanation of how this bonus increases their sales conversion or speeds up results",
      "objectionSolved": "The specific customer objection this bonus handles and eliminates (e.g. 'solves lack of technical skills concern')"
    }
  ],
  "bonusPage": {
    "headline": "Attention-grabbing, conversion-optimized headline for the bonus page",
    "subheadline": "Compelling subheadline outlining the value and limited-time offer",
    "ctaText": "Claim Your Product & Special Bonuses Now",
    "bonusStackDescription": "Summary highlighting the combined value of all 10 bonuses",
    "scarcitySection": "Urgent copy specifying that this offer is highly limited (e.g. expiring on date or limited to first 50 action takers)",
    "closingSection": "Reassuring final words eliminating risk, encouraging action, and outlining next steps",
    "htmlTemplate": "Leave this field as an empty string \"\". The backend will automatically generate the premium HTML structure using your copy."
  },
  "emails": [
    {
      "type": "announcement",
      "subject": "Announcement email subject line",
      "previewText": "Email teaser preview text",
      "body": "Email body copy. Use placeholders like [Name] and [Affiliate Link].",
      "ctaText": "Secure Your Copy + Bonuses Here"
    }
  ]
}

Constraints:
1. "bonuses" MUST contain exactly 10 highly relevant, high-value, complementary bonus ideas (NOT generic ones).
2. "emails" MUST contain exactly 4 emails with types: "announcement", "benefits", "faq", and "last-chance".
3. Every field must be populated with rich, high-quality, conversion-optimized text. No empty values or placeholders (except in the email body for names/links).`;

    const userPrompt = `Here is the scraped content from the product sales page:
---
${contentToAnalyze}
---

Generate the affiliate marketing suite JSON matching the specified schema. Make sure the 'htmlTemplate' inside 'bonusPage' is fully formatted, readable HTML ready for previewing.`;

    const messages = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ];

    let apiResultText = "";
    let attempts = 0;
    const maxAttempts = 3;
    let parsedResult: any = null;

    while (attempts < maxAttempts) {
      attempts++;
      try {
        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${apiKey}`,
            "HTTP-Referer": "https://github.com/google/antigravity", // fallback referer
            "X-Title": "Affiliate Bonus Generator"
          },
          body: JSON.stringify({
            model: model,
            messages: messages,
            response_format: { type: "json_object" },
            temperature: 0.3
          }),
          signal: AbortSignal.timeout(60000) // 60-second timeout for LLM
        });

        if (!response.ok) {
          const errText = await response.text();
          throw new Error(`OpenRouter API responded with ${response.status}: ${errText}`);
        }

        const data = await response.json();
        apiResultText = data.choices?.[0]?.message?.content || "";
        
        if (!apiResultText) {
          throw new Error("Empty content returned from OpenRouter");
        }

        // Try parsing JSON
        parsedResult = extractJson(apiResultText);

        // Populate HTML template dynamically on the server
        if (parsedResult && parsedResult.bonusPage && Array.isArray(parsedResult.bonuses)) {
          parsedResult.bonusPage.htmlTemplate = buildHtmlPage(
            parsedResult.analysis || {}, 
            parsedResult.bonuses, 
            parsedResult.bonusPage
          );
        }

        // Validate structure
        if (isValidApiResponse(parsedResult)) {
          break; // Parsing and validation succeeded, break loop
        } else {
          console.warn("Parsed object structure was invalid. Attempting correction...");
          throw new Error("Invalid structure returned according to schema requirements.");
        }

      } catch (err: any) {
        console.error(`Attempt ${attempts} failed:`, err.message);
        
        const isTimeout = err.name === 'TimeoutError' || err.message.includes('timeout') || err.message.includes('aborted');
        
        if (attempts >= maxAttempts || isTimeout) {
          return NextResponse.json(
            { 
              error: isTimeout 
                ? "OpenRouter API connection timed out. The request took longer than 60 seconds. Please try again or switch to Google Gemini 2.5 Flash."
                : `AI generation failed after multiple attempts. Error: ${err.message}`, 
              rawResponse: apiResultText 
            },
            { status: isTimeout ? 504 : 500 }
          );
        }

        // Only append to history if we actually got a response to correct.
        // If it was a network timeout or completely empty, we do not pollute the chat history.
        if (apiResultText && apiResultText.trim().length > 0) {
          messages.push({
            role: "assistant",
            content: apiResultText
          });
          messages.push({
            role: "user",
            content: `The response provided was invalid or failed JSON parsing. Error detail: ${err.message}. Please rewrite the response, ensuring that:
1. It is a strictly valid JSON object matching the exact schema.
2. No text exists outside of the JSON structure.
3. Every single field is correctly populated.
4. The "bonuses" array contains exactly 10 items.
5. The "emails" array contains exactly 4 items (announcement, benefits, faq, last-chance).
Ensure all trailing commas, unescaped characters, or broken blocks are corrected.`
          });
        }
      }
    }

    return NextResponse.json(parsedResult);

  } catch (error: any) {
    console.error("Unhandled error in API route:", error);
    return NextResponse.json(
      { error: `An unexpected server error occurred: ${error.message || error}` },
      { status: 500 }
    );
  }
}
